# Config file for automatic testing at travis-ci.org

sudo: false

language: python

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
    - GDALINST=$HOME/gdalinstall
    - GDALBUILD=$HOME/gdalbuild
    - PROJINST=$HOME/gdalinstall
    - PROJBUILD=$HOME/projbuild

jobs:
  include:
    - python: "3.6"
      env:
        GDALVERSION="2.3.3"
        PROJVERSION="4.9.3"
    - python: "3.6"
      env:
        GDALVERSION="2.4.4"
        PROJVERSION="4.9.3"
    - python: "3.7"
      env:
        GDALVERSION="2.4.4"
        PROJVERSION="4.9.3"
    - python: "3.8"
      env:
        GDALVERSION="2.4.4"
        PROJVERSION="4.9.3"
    - python: "3.6"
      env:
        GDALVERSION="3.0.4"
        PROJVERSION="6.2.1"
    - python: "3.7"
      env:
        GDALVERSION="3.0.4"
        PROJVERSION="6.2.1"
    - python: "3.8"
      env:
        GDALVERSION="3.0.4"
        PROJVERSION="6.2.1"
    - python: "3.8"
      env:
        GDALVERSION="master"
        PROJVERSION="6.2.1"
  allow_failures:
    - env:
        GDALVERSION="master"
        PROJVERSION="6.2.1"

before_install:
  - python -m pip install -U pip
  - python -m pip install wheel
  - export PATH=$GDALINST/gdal-$GDALVERSION/bin:$PATH
  - export LD_LIBRARY_PATH=$GDALINST/gdal-$GDALVERSION/lib:$LD_LIBRARY_PATH
  - . ./scripts/travis_proj_install.sh
  - travis_wait 20 . ./scripts/travis_gdal_install.sh
  - export GDAL_DATA=$GDALINST/gdal-$GDALVERSION/share/gdal
  - export PROJ_LIB=$GDALINST/gdal-$GDALVERSION/share/proj

install:
  - pip install -U tox-travis

script: tox
