# Config file for automatic testing at travis-ci.org

sudo: false

language: python

python:
  - 3.7
  - 3.6

install:
  - sudo apt-get -qq -y update
  - sudo apt-get install -y libgdal-dev
  - pip install -U tox-travis

jobs:
  include:
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial

script: tox
